# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/goinstant/pods-specs-public.git'

use_modular_headers!
use_frameworks!


target 'BBZVideoEngine' do
    pod 'JRSwizzle'
end



